version: "3.9"
services:
  minio-storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: 
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - /docker/minio:/bucket_data

  create-buckets:
    image: minio/mc
    depends_on:
      - minio-storage
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER-root_user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD-root_password}
      - MINIO_TEST_USER=${MINIO_TEST_USER-dev}
      - MINIO_TEST_PASSWORD=${MINIO_TEST_PASSWORD-dev_password}
      - BUCKET_NAME=${BUCKET_NAME-test-bucket}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-storage:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc admin user add myminio $${MINIO_TEST_USER} $${MINIO_TEST_PASSWORD};
      /usr/bin/mc admin policy set myminio readwrite user=$${MINIO_TEST_USER};
      /usr/bin/mc mb --with-versioning myminio/$${BUCKET_NAME};
      /usr/bin/mc anonymous set none myminio/$${BUCKET_NAME};
      exit 0;
      "

  ml-model-training:
    build:
      context: .
      dockerfile: training/Dockerfile
    image: auto-mpg-ml-model-training-img:local
    depends_on: 
      - minio-storage
      - create-buckets
    volumes:
      - /app/artifacts:/app/artifacts
  fastapi:
    build:
      context: .
      dockerfile: serving/Dockerfile
    image: auto-mpg-fastapi-img:local
    ports:
      - "80:80"
    depends_on:
      - ml-model-training
    volumes:
      - /app/artifacts:/app/artifacts