version: "3.9"
services:
  minio-storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: 
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER-root_user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD-root_password}
      - BUCKET_NAME=${BUCKET_NAME-test-bucket}
    volumes:
      - /docker/minio:/bucket_data

  create-buckets:
    image: minio/mc
    depends_on:
      - minio-storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-storage:9000 ${MINIO_ROOT_USER-root_user} ${MINIO_ROOT_PASSWORD-root_password};
      /usr/bin/mc mb myminio/${BUCKET_NAME-test-bucket};
      /usr/bin/mc policy set public myminio/${BUCKET_NAME-test_bucket};
      exit 0;
      "

  ml-model-training:
    build:
      context: .
      dockerfile: training/Dockerfile
    image: auto-mpg-ml-model-training-img:local
    depends_on: 
      - minio-storage
      - create-buckets
    volumes:
      - /app/artifacts:/app/artifacts
  fastapi:
    build:
      context: .
      dockerfile: serving/Dockerfile
    image: auto-mpg-fastapi-img:local
    ports:
      - "80:80"
    depends_on:
      - ml-model-training
    volumes:
      - /app/artifacts:/app/artifacts