fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pre-commit/mirrors-pylint
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--strict]